config:
  dockerfile: .woloxci/Dockerfile
  project_name: galicia-movilidad-rails

services:
  - postgres
  - redis

steps:
  analysis:
    - bundle exec rubocop -P --format simple
    - bundle exec rubycritic --path ./analysis --minimum-score 80 --no-browser
    - overcommit --sign && overcommit --sign pre-commit && overcommit --run
  setup_db:
    - bundle exec rails db:create
    - bundle exec rails db:schema:load
  test:
    - bundle exec rspec
  security:
    - bundle exec brakeman --exit-on-error

environment:
  RAILS_ENV: test
  GIT_COMMITTER_NAME: a
  GIT_COMMITTER_EMAIL: b
  LANG: C.UTF-8
  GIT_AUTHOR_NAME: Test Wolox
  GIT_AUTHOR_EMAIL: test@wolox.com.ar
  EXCLUDED_FROM_AREAS: "['1001', '1002', 'TEMP']"
  INCLUDE_CHILDREN_AS_AREAS: "['1001']"
  ROOT_ORGANIZATION_UNIT_ID: ROOT
  PEOPLE_NET_CERT_FILE: ''
